version: '3.7'

services:
  backend:
    container_name: showfilesserver
    build:
      context: ./DotNetServer
      dockerfile: Dockerfile
    ports:
      - "44314:80"
    volumes:
      - ~/Containers:/repo
  frontend:
    container_name: showfilesclient
    build:
      context: ./AngularClient
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
